#!/usr/bin/env bash
set -euo pipefail

ENV_FILE="${1:-configs/unchain-kv.env}"
test -f "$ENV_FILE"
set -a
source "$ENV_FILE"
set +a

ROOT="${UNCHAIN_KV_REMOTE_ROOT}"
RUN_ROOT="${ROOT}/runs/${UNCHAIN_KV_RUN_ID:-smoke}"
mkdir -p "$RUN_ROOT/logs" "$RUN_ROOT/trace"

require_gpu() {
  local gpu_id="$1"
  if ! nvidia-smi -L | grep -q "^GPU ${gpu_id}:"; then
    echo "Configured GPU ${gpu_id} is not visible to nvidia-smi" >&2
    exit 2
  fi
}

require_gpu "${UNCHAIN_KV_DECODE_GPU}"
require_gpu "${UNCHAIN_KV_PREFILL_GPU}"

wait_api_ready() {
  local host="$1"
  local port="$2"
  local retries="${UNCHAIN_KV_READY_RETRIES:-120}"
  local sleep_s="${UNCHAIN_KV_READY_SLEEP_S:-5}"
  for _ in $(seq 1 "$retries"); do
    if curl -fsS "http://${host}:${port}/v1/models" >/dev/null 2>&1; then
      return 0
    fi
    sleep "$sleep_s"
  done
  echo "Timed out waiting for ${host}:${port}" >&2
  exit 3
}

rm_args=()
if [[ "${UNCHAIN_KV_KEEP_CONTAINERS:-0}" != "1" ]]; then
  rm_args=(--rm)
fi

docker run -d "${rm_args[@]}" --name unchain-kv-decode \
  --gpus "device=${UNCHAIN_KV_DECODE_GPU}" \
  --network host \
  -v "${ROOT}:${ROOT}" \
  -v "${UNCHAIN_KV_MODEL}:${UNCHAIN_KV_MODEL}:ro" \
  -e PYTHONPATH="${ROOT}/src" \
  -e UNCHAIN_KV_BIND="${UNCHAIN_KV_DECODE_ENDPOINT}" \
  -e UNCHAIN_KV_PEER="${UNCHAIN_KV_PREFILL_ENDPOINT}" \
  -e UNCHAIN_KV_TRANSPORT=tcp \
  -e UNCHAIN_KV_TCP_LIB="${UNCHAIN_KV_TCP_LIB:-}" \
  -e UNCHAIN_KV_TRACE="${RUN_ROOT}/trace/decode.jsonl" \
  -e UNCHAIN_KV_TRACE_CHUNKS="${UNCHAIN_KV_TRACE_CHUNKS:-0}" \
  -e UNCHAIN_KV_CHUNK_BYTES="${UNCHAIN_KV_CHUNK_BYTES}" \
  -e UNCHAIN_KV_RECV_BUFFER_BYTES="${UNCHAIN_KV_RECV_BUFFER_BYTES:-16777216}" \
  -e UNCHAIN_KV_MAX_BLOCKS="${UNCHAIN_KV_MAX_BLOCKS:-1}" \
  -e UNCHAIN_KV_GRANT_WINDOW="${UNCHAIN_KV_GRANT_WINDOW:-0}" \
  -e UNCHAIN_KV_RESTORE_AHEAD="${UNCHAIN_KV_RESTORE_AHEAD:-0}" \
  -e UNCHAIN_KV_BULK_DECODE="${UNCHAIN_KV_BULK_DECODE:-0}" \
  -e UNCHAIN_KV_KV_MAJOR_PAYLOAD="${UNCHAIN_KV_KV_MAJOR_PAYLOAD:-0}" \
  -e UNCHAIN_KV_NATIVE_LAYOUT_PAYLOAD="${UNCHAIN_KV_NATIVE_LAYOUT_PAYLOAD:-0}" \
  -e UNCHAIN_KV_PINNED_STAGING="${UNCHAIN_KV_PINNED_STAGING:-0}" \
  -e UNCHAIN_KV_HOST_MIRROR_LAYERS="${UNCHAIN_KV_HOST_MIRROR_LAYERS:-0}" \
  -e UNCHAIN_KV_HOST_MIRROR_BYTES="${UNCHAIN_KV_HOST_MIRROR_BYTES:-0}" \
  -e UNCHAIN_KV_REQUEST_SPOOL_BYTES="${UNCHAIN_KV_REQUEST_SPOOL_BYTES:-0}" \
  -e UNCHAIN_KV_REQUEST_SPOOL_AUTO="${UNCHAIN_KV_REQUEST_SPOOL_AUTO:-0}" \
  -e UNCHAIN_KV_HOST_GUARD_BYTES="${UNCHAIN_KV_HOST_GUARD_BYTES:-2147483648}" \
  -e UNCHAIN_KV_GPU_GUARD_BYTES="${UNCHAIN_KV_GPU_GUARD_BYTES:-536870912}" \
  -e UNCHAIN_KV_AUTO_SPOOL_HARD_BYTES="${UNCHAIN_KV_AUTO_SPOOL_HARD_BYTES:-0}" \
  -e UNCHAIN_KV_SPOOL_PRESSURE_RATIO="${UNCHAIN_KV_SPOOL_PRESSURE_RATIO:-1.15}" \
  -e UNCHAIN_KV_SPOOL_LIVE_CAP_FILE="${UNCHAIN_KV_SPOOL_LIVE_CAP_FILE:-}" \
  -e UNCHAIN_KV_CODEC="${UNCHAIN_KV_CODEC:-}" \
  -e UNCHAIN_KV_CODEC_MIN_BLOCKS="${UNCHAIN_KV_CODEC_MIN_BLOCKS:-0}" \
  -e UNCHAIN_KV_CODEC_GPU_BYTES="${UNCHAIN_KV_CODEC_GPU_BYTES:-0}" \
  -e UNCHAIN_KV_SPLITZIP_TOP16="${UNCHAIN_KV_SPLITZIP_TOP16:-0}" \
  -e UNCHAIN_KV_SPLITZIP_TOP16_MAX_COOLDOWN="${UNCHAIN_KV_SPLITZIP_TOP16_MAX_COOLDOWN:-32}" \
  -e UNCHAIN_KV_SPLITZIP_NATIVE_DECODE="${UNCHAIN_KV_SPLITZIP_NATIVE_DECODE:-0}" \
  -e UNCHAIN_KV_SPLITZIP_CHUNKS="${UNCHAIN_KV_SPLITZIP_CHUNKS:-1}" \
  -e UNCHAIN_KV_CODEC_WRITEBACK="${UNCHAIN_KV_CODEC_WRITEBACK:-}" \
  -e UNCHAIN_KV_CODEC_WRITEBACK_STRICT="${UNCHAIN_KV_CODEC_WRITEBACK_STRICT:-0}" \
  -e UNCHAIN_KV_GPU_PACK_LAYERS="${UNCHAIN_KV_GPU_PACK_LAYERS:-0}" \
  -e UNCHAIN_KV_GPU_PACK_BYTES="${UNCHAIN_KV_GPU_PACK_BYTES:-0}" \
  -e UNCHAIN_KV_GPU_PACK_STRICT="${UNCHAIN_KV_GPU_PACK_STRICT:-0}" \
  -e UNCHAIN_KV_PAYLOAD_READY="${UNCHAIN_KV_PAYLOAD_READY:-1}" \
  -e UNCHAIN_KV_EARLY_STAGE="${UNCHAIN_KV_EARLY_STAGE:-0}" \
  -e UNCHAIN_KV_EARLY_STAGE_PACK_ONLY="${UNCHAIN_KV_EARLY_STAGE_PACK_ONLY:-0}" \
  -e UNCHAIN_KV_SEND_WORKERS="${UNCHAIN_KV_SEND_WORKERS:-1}" \
  -e UNCHAIN_KV_SEND_INFLIGHT="${UNCHAIN_KV_SEND_INFLIGHT:-0}" \
  -e UNCHAIN_KV_LAYER_GROUP_SIZE="${UNCHAIN_KV_LAYER_GROUP_SIZE:-1}" \
  -e UNCHAIN_KV_LAYER_DELAY_S="${UNCHAIN_KV_LAYER_DELAY_S:-0}" \
  -e UNCHAIN_KV_SEND_GAP_S="${UNCHAIN_KV_SEND_GAP_S:-0}" \
  -e UNCHAIN_KV_SEND_GAP_EVERY="${UNCHAIN_KV_SEND_GAP_EVERY:-1}" \
  -e UNCHAIN_KV_WAIT_TIMEOUT_S="${UNCHAIN_KV_WAIT_TIMEOUT_S}" \
  -e UNCHAIN_KV_EXPECTED_LAYERS="${UNCHAIN_KV_EXPECTED_LAYERS}" \
  -e UNCHAIN_KV_VLLM_ARGS="${UNCHAIN_KV_VLLM_ARGS:-}" \
  -e UNCHAIN_KV_EXTENT_ALLOC=off \
  -e UNCHAIN_KV_EXTENT_RESERVE_BLOCKS=0 \
  "${UNCHAIN_KV_IMAGE}" \
  bash -lc "python3 -m unchain_kv.patch_vllm \$(python3 -c 'from pathlib import Path; import vllm; print(Path(vllm.__file__).resolve().parents[1])') && \
    vllm serve ${UNCHAIN_KV_MODEL} \
      --host ${UNCHAIN_KV_DECODE_HOST} \
      --port ${UNCHAIN_KV_DECODE_API_PORT} \
      --kv-transfer-config '{\"kv_connector\":\"UnchainKVConnector\",\"kv_role\":\"kv_consumer\"}' \
      \${UNCHAIN_KV_VLLM_ARGS:-}" \
  > "${RUN_ROOT}/logs/decode.container.log" 2>&1

if [[ "${UNCHAIN_KV_SEQUENTIAL_LAUNCH:-0}" == "1" ]]; then
  wait_api_ready "${UNCHAIN_KV_DECODE_HOST}" "${UNCHAIN_KV_DECODE_API_PORT}"
fi

docker run -d "${rm_args[@]}" --name unchain-kv-prefill \
  --gpus "device=${UNCHAIN_KV_PREFILL_GPU}" \
  --network host \
  -v "${ROOT}:${ROOT}" \
  -v "${UNCHAIN_KV_MODEL}:${UNCHAIN_KV_MODEL}:ro" \
  -e PYTHONPATH="${ROOT}/src" \
  -e UNCHAIN_KV_BIND="${UNCHAIN_KV_PREFILL_ENDPOINT}" \
  -e UNCHAIN_KV_PEER="${UNCHAIN_KV_DECODE_ENDPOINT}" \
  -e UNCHAIN_KV_TRANSPORT=tcp \
  -e UNCHAIN_KV_TCP_LIB="${UNCHAIN_KV_TCP_LIB:-}" \
  -e UNCHAIN_KV_TRACE="${RUN_ROOT}/trace/prefill.jsonl" \
  -e UNCHAIN_KV_TRACE_CHUNKS="${UNCHAIN_KV_TRACE_CHUNKS:-0}" \
  -e UNCHAIN_KV_CHUNK_BYTES="${UNCHAIN_KV_CHUNK_BYTES}" \
  -e UNCHAIN_KV_RECV_BUFFER_BYTES="${UNCHAIN_KV_RECV_BUFFER_BYTES:-16777216}" \
  -e UNCHAIN_KV_MAX_BLOCKS="${UNCHAIN_KV_MAX_BLOCKS:-1}" \
  -e UNCHAIN_KV_GRANT_WINDOW="${UNCHAIN_KV_GRANT_WINDOW:-0}" \
  -e UNCHAIN_KV_RESTORE_AHEAD="${UNCHAIN_KV_RESTORE_AHEAD:-0}" \
  -e UNCHAIN_KV_BULK_DECODE="${UNCHAIN_KV_BULK_DECODE:-0}" \
  -e UNCHAIN_KV_KV_MAJOR_PAYLOAD="${UNCHAIN_KV_KV_MAJOR_PAYLOAD:-0}" \
  -e UNCHAIN_KV_NATIVE_LAYOUT_PAYLOAD="${UNCHAIN_KV_NATIVE_LAYOUT_PAYLOAD:-0}" \
  -e UNCHAIN_KV_PINNED_STAGING="${UNCHAIN_KV_PINNED_STAGING:-0}" \
  -e UNCHAIN_KV_HOST_MIRROR_LAYERS="${UNCHAIN_KV_HOST_MIRROR_LAYERS:-0}" \
  -e UNCHAIN_KV_HOST_MIRROR_BYTES="${UNCHAIN_KV_HOST_MIRROR_BYTES:-0}" \
  -e UNCHAIN_KV_REQUEST_SPOOL_BYTES="${UNCHAIN_KV_REQUEST_SPOOL_BYTES:-0}" \
  -e UNCHAIN_KV_REQUEST_SPOOL_AUTO="${UNCHAIN_KV_REQUEST_SPOOL_AUTO:-0}" \
  -e UNCHAIN_KV_HOST_GUARD_BYTES="${UNCHAIN_KV_HOST_GUARD_BYTES:-2147483648}" \
  -e UNCHAIN_KV_GPU_GUARD_BYTES="${UNCHAIN_KV_GPU_GUARD_BYTES:-536870912}" \
  -e UNCHAIN_KV_AUTO_SPOOL_HARD_BYTES="${UNCHAIN_KV_AUTO_SPOOL_HARD_BYTES:-0}" \
  -e UNCHAIN_KV_SPOOL_PRESSURE_RATIO="${UNCHAIN_KV_SPOOL_PRESSURE_RATIO:-1.15}" \
  -e UNCHAIN_KV_SPOOL_LIVE_CAP_FILE="${UNCHAIN_KV_SPOOL_LIVE_CAP_FILE:-}" \
  -e UNCHAIN_KV_CODEC="${UNCHAIN_KV_CODEC:-}" \
  -e UNCHAIN_KV_CODEC_MIN_BLOCKS="${UNCHAIN_KV_CODEC_MIN_BLOCKS:-0}" \
  -e UNCHAIN_KV_CODEC_GPU_BYTES="${UNCHAIN_KV_CODEC_GPU_BYTES:-0}" \
  -e UNCHAIN_KV_SPLITZIP_TOP16="${UNCHAIN_KV_SPLITZIP_TOP16:-0}" \
  -e UNCHAIN_KV_SPLITZIP_TOP16_MAX_COOLDOWN="${UNCHAIN_KV_SPLITZIP_TOP16_MAX_COOLDOWN:-32}" \
  -e UNCHAIN_KV_SPLITZIP_NATIVE_DECODE="${UNCHAIN_KV_SPLITZIP_NATIVE_DECODE:-0}" \
  -e UNCHAIN_KV_SPLITZIP_CHUNKS="${UNCHAIN_KV_SPLITZIP_CHUNKS:-1}" \
  -e UNCHAIN_KV_CODEC_WRITEBACK="${UNCHAIN_KV_CODEC_WRITEBACK:-}" \
  -e UNCHAIN_KV_CODEC_WRITEBACK_STRICT="${UNCHAIN_KV_CODEC_WRITEBACK_STRICT:-0}" \
  -e UNCHAIN_KV_GPU_PACK_LAYERS="${UNCHAIN_KV_GPU_PACK_LAYERS:-0}" \
  -e UNCHAIN_KV_GPU_PACK_BYTES="${UNCHAIN_KV_GPU_PACK_BYTES:-0}" \
  -e UNCHAIN_KV_GPU_PACK_STRICT="${UNCHAIN_KV_GPU_PACK_STRICT:-0}" \
  -e UNCHAIN_KV_PAYLOAD_READY="${UNCHAIN_KV_PAYLOAD_READY:-1}" \
  -e UNCHAIN_KV_EARLY_STAGE="${UNCHAIN_KV_EARLY_STAGE:-0}" \
  -e UNCHAIN_KV_EARLY_STAGE_PACK_ONLY="${UNCHAIN_KV_EARLY_STAGE_PACK_ONLY:-0}" \
  -e UNCHAIN_KV_SEND_WORKERS="${UNCHAIN_KV_SEND_WORKERS:-1}" \
  -e UNCHAIN_KV_SEND_INFLIGHT="${UNCHAIN_KV_SEND_INFLIGHT:-0}" \
  -e UNCHAIN_KV_LAYER_GROUP_SIZE="${UNCHAIN_KV_LAYER_GROUP_SIZE:-1}" \
  -e UNCHAIN_KV_LAYER_DELAY_S="${UNCHAIN_KV_LAYER_DELAY_S:-0}" \
  -e UNCHAIN_KV_SEND_GAP_S="${UNCHAIN_KV_SEND_GAP_S:-0}" \
  -e UNCHAIN_KV_SEND_GAP_EVERY="${UNCHAIN_KV_SEND_GAP_EVERY:-1}" \
  -e UNCHAIN_KV_EXPECTED_LAYERS="${UNCHAIN_KV_EXPECTED_LAYERS}" \
  -e UNCHAIN_KV_VLLM_ARGS="${UNCHAIN_KV_VLLM_ARGS:-}" \
  -e UNCHAIN_KV_EXTENT_ALLOC="${UNCHAIN_KV_EXTENT_ALLOC:-off}" \
  -e UNCHAIN_KV_EXTENT_RESERVE_BLOCKS="${UNCHAIN_KV_EXTENT_RESERVE_BLOCKS:-0}" \
  "${UNCHAIN_KV_IMAGE}" \
  bash -lc "python3 -m unchain_kv.patch_vllm \$(python3 -c 'from pathlib import Path; import vllm; print(Path(vllm.__file__).resolve().parents[1])') && \
    vllm serve ${UNCHAIN_KV_MODEL} \
      --host ${UNCHAIN_KV_PREFILL_HOST} \
      --port ${UNCHAIN_KV_PREFILL_API_PORT} \
      --kv-transfer-config '{\"kv_connector\":\"UnchainKVConnector\",\"kv_role\":\"kv_producer\"}' \
      \${UNCHAIN_KV_VLLM_ARGS:-}" \
  > "${RUN_ROOT}/logs/prefill.container.log" 2>&1

echo "$RUN_ROOT"
